<?php

namespace Erenkucukersoftware\BrugsMigrationTool;


class Constants
{
  public static $CUSTOM_GROUP  = [
    'fragile','clearance','outdoor_safe','top_seller','washable','recycled','new_arrival','featured'
  ];
  public static $ENTITY_TYPES = ['Products'];

  public static $UPDATEABLE_PRODUCT_FIELDS = [
    'tags', 'descriptionHtml', 'metafields','variants','images', 'variants.metafields', 'new_metafields', 'title'
  ];
  public static $SPECIAL_MATERIAL_CATEGORIES = [
    'bamboo', 'cotton', 'hemp', 'jute', 'leather','sisal', 'fiber', 'other', 'recycled', 'silk', 'synthetics', 'wool'
  ];
  public static $SPECIAL_STYLE_CATEGORIES = [
    'animal', 'aztec rugs', 'bohemian', 'coastal', 'contemporary', 'country & floral', 'farmhouse', 'geometric', 'kids & novelty', 'moroccan rugs', 'one of a kind', 'outdoor', 'persian rugs', 'shags', 'solid & striped', 'southwestern', 'traditional', 'transitional', 'vintage'
  ];
  /*
  public static $SPECIAL_COLOR_CATEGORIES = [
            'Grey' => 'Black & Grey Rugs',
            'Gray' => 'Black & Grey Rugs',
            'Neutral' => 'White Rugs',
            'Pink' => 'Pink Rugs',
            'Brown' => 'Brown Rugs',
            'Natural' => 'White Rugs',
            'Green' => 'Green Rugs',
            'Tan' => 'White Rugs',
            'Beige' => 'White Rugs',
            'Orange' => 'Orange Rugs',
            'Black' => 'Black & Grey Rugs',
            'Red' => array('Red Rugs', 'Burgundies', 'Pink Rugs'),
            'Blue' => 'Blue Rugs',
            'Yellow' => 'Yellow & Gold Rugs',
            'Off-White' => 'White Rugs',
            'Khaki' => 'Yellow & Gold Rugs',
            'White' => 'White Rugs',
            'Purple' => 'Purple Rugs',
            'Navy' => 'Blue Rugs',
            'Silver' => 'Black & Grey Rugs',
            'Multi-colored' => 'Multi Color Rugs',
            'Kahki' => 'Yellow & Gold Rugs',
            'Black & White' => 'Black & Grey Rugs',
            'Gold' => 'Yellow & Gold Rugs',
            'Copper' => array('Yellow & Gold Rugs', 'Brown Rugs'),
            'Light Yellow' => 'Yellow & Gold Rugs',
            'Denim' => 'Blue Rugs',
            'Bright Pink' => 'Pink Rugs',
            'Pale Blue' => 'Blue Rugs',
            'Teal' => array('Green Rugs', 'Blue Rugs'),
            'Light Brown' => 'Brown Rugs',
            'Dark Brown' => 'Brown Rugs',
            'Light Gray' => 'Black & Grey Rugs',
            'Bright Yellow' => 'Yellow & Gold Rugs',
            'Dark Blue' => 'Blue Rugs',
            'Dark Purple' => 'Purple Rugs',
            'Metallic' => 'Black & Grey Rugs'
  ];
  */
  public static $SPECIAL_COLOR_CATEGORIES = [
    'Admiral Blue' => 'Blue Rugs',
    'Apple Green' => 'Green Rugs',
    'Aqua' => 'Blue Rugs',
    'Arctic Blue' => 'Blue Rugs',
    'Arctic Ivory' => 'Tan & Ivories Rugs',
    'Arctic Sky' => 'Blue Rugs',
    'Arctic Stone' => 'Tan & Ivories Rugs',
    'Azo Blue' => 'Blue Rugs',
    'Beachhouse' => 'Brown Rugs',
    'Beige' => 'Tan & Ivories Rugs',
    'Bisque' => 'Tan & Ivories Rugs',
    'Black' => 'Black & Grey Rugs',
    'Black White' => 'Black & Grey Rugs',
    'Blue' => 'Blue Rugs',
    'Blush' => 'Pink Rugs',
    'Bone' => 'Tan & Ivories Rugs',
    'Brick' => 'Red Rugs',
    'Brick Red' => 'Red Rugs',
    'Bright Blue' => 'Blue Rugs',
    'Bright Orange' => 'Orange Rugs',
    'Bright Pink' => 'Pink Rugs',
    'Bright Purple' => 'Purple Rugs',
    'Bright Red' => 'Red Rugs',
    'Bright Yellow' => 'Yellow & Gold Rugs',
    'Brown' => 'Brown Rugs',
    'Burgundy' => 'Red Rugs',
    'Burnt Orange' => 'Orange Rugs',
    'Butter' => 'Tan & Ivories Rugs',
    'Camel' => 'Tan & Ivories Rugs',
    'Champagne' => 'Tan & Ivories Rugs',
    'Charcoal' => 'Black & Grey Rugs',
    'Cherry' => 'Red Rugs',
    'Chocolate' => 'Brown Rugs',
    'Chocolate Brown' => 'Brown Rugs',
    'Clay' => 'Tan & Ivories Rugs',
    'Cloud Gray' => 'Black & Grey Rugs',
    'Cobalt' => 'Blue Rugs',
    'Copper' => 'Brown Rugs',
    'Coral' => 'Orange Rugs',
    'Cream' => 'Tan & Ivories Rugs',
    'Crimson Red' => 'Red Rugs',
    'Dark Blue' => 'Blue Rugs',
    'Dark Brown' => 'Brown Rugs',
    'Dark Coral' => 'Orange Rugs',
    'Dark Green' => 'Green Rugs',
    'Dark Multi' => 'Multi Color Rugs',
    'Dark Orange' => 'Orange Rugs',
    'Dark Purple' => 'Purple Rugs',
    'Dark Red' => 'Red Rugs',
    'Denim' => 'Blue Rugs',
    'Denim Blue' => 'Blue Rugs',
    'Driftwood' => 'Black & Grey Rugs',
    'Eggplant' => 'Purple Rugs',
    'Emerald' => 'Green Rugs',
    'Faded Driftwood' => 'Black & Grey Rugs',
    'Faded Indigo' => 'Blue Rugs',
    'Forest' => 'Green Rugs',
    'Forest Green' => 'Green Rugs',
    'Fuschia' => 'Pink Rugs',
    'Garnet' => 'Red Rugs',
    'Gold' => 'Yellow & Gold Rugs',
    'Grass Green' => 'Green Rugs',
    'Gray' => 'Black & Grey Rugs',
    'Gray Blue' => 'Blue Rugs',
    'Green' => 'Green Rugs',
    'Grey' => 'Black & Grey Rugs',
    'Harbor Blue' => 'Blue Rugs',
    'Harbor Blue White' => 'Blue Rugs',
    'Hot Pink' => 'Pink Rugs',
    'Ice Blue' => 'Blue Rugs',
    'Indigo' => 'Blue Rugs',
    'Ivory' => 'White Rugs',
    'Kelly Green' => 'Green Rugs',
    'Khaki' => 'Brown Rugs',
    'Kiwi' => 'Green Rugs',
    'Lambswool' => 'Brown Rugs',
    'Lavender' => 'Purple Rugs',
    'Lemon' => 'Yellow & Gold Rugs',
    'Light Blue' => 'Blue Rugs',
    'Light Gray' => 'Black & Grey Rugs',
    'Light Green' => 'Green Rugs',
    'Light Multi' => 'Multi Color Rugs',
    'Light Yellow' => 'Yellow & Gold Rugs',
    'Lilac' => 'Purple Rugs',
    'Lime' => 'Green Rugs',
    'Lime Green' => 'Green Rugs',
    'Magenta' => 'Pink Rugs',
    'Mauve' => 'Purple Rugs',
    'Medium Gray' => 'Black & Grey Rugs',
    'Metallic - Champagne' => 'Yellow & Gold Rugs',
    'Metallic - Copper' => 'Brown Rugs',
    'Metallic - Gold' => 'Yellow & Gold Rugs',
    'Metallic - Silver' => 'Black & Grey Rugs',
    'Mint' => 'Green Rugs',
    'Mocha' => 'Brown Rugs',
    'Moss' => 'Green Rugs',
    'Multi' => 'Multi Color Rugs',
    'Multi Black' => 'Black & Grey Rugs',
    'Multi Brown' => 'Brown Rugs',
    'Multi Red' => 'Red Rugs',
    'Multi White' => 'White Rugs',
    'Mustard' => 'Yellow & Gold Rugs',
    'Muted Blue' => 'Blue Rugs',
    'Natural' => 'Tan & Ivories Rugs',
    'Natural Blue' => 'Blue Rugs',
    'Natural Driftwood' => 'Black & Grey Rugs',
    'Natural Gray' => 'Black & Grey Rugs',
    'Natural Grey' => 'Black & Grey Rugs',
    'Navy' => 'Blue Rugs',
    'Navy Blue' => 'Blue Rugs',
    'Navy Tonal' => 'Blue Rugs',
    'Neutral' => 'Tan & Ivories Rugs',
    'Nutmeg' => ['Orange Rugs','Brown Rugs'],
    'Off White' => 'White Rugs',
    'Off-White' => 'White Rugs',
    'Olive' => 'Green Rugs',
    'Onyx Black' => 'Black & Grey Rugs',
    'Orange' => 'Orange Rugs',
    'Pale Blue' => 'Blue Rugs',
    'Pale Pink' => 'Pink Rugs',
    'Pastel Pink' => 'Pink Rugs',
    'Peach' => 'Orange Rugs',
    'Pear' => 'Green Rugs',
    'Pewter' => 'Black & Grey Rugs',
    'Pink' => 'Pink Rugs',
    'Plum' => 'Purple Rugs',
    'Poppy Red' => 'Red Rugs',
    'Purple' => 'Purple Rugs',
    'Rainbow' => 'Multi Color Rugs',
    'Raspberry' => 'Pink Rugs',
    'Red' => 'Red Rugs',
    'Rose' => 'Pink Rugs',
    'Royal Blue' => 'Blue Rugs',
    'Royal Denim' => 'Blue Rugs',
    'Rust' => ['Orange Rugs','Brown Rugs'],
    'Saffron' => ['Orange Rugs ',' Yellow & Gold Rugs'],
    'Sage' => 'Green Rugs',
    'Sage Green' => 'Green Rugs',
    'Sand' => 'Tan & Ivories Rugs',
    'Sea Foam' => 'Green Rugs',
    'Seashell' => 'White Rugs',
    'Silver' => 'Black & Grey Rugs',
    'Silver Blue' => 'Blue Rugs',
    'Silver Gray' => 'Black & Grey Rugs',
    'Silverstone' => 'Black & Grey Rugs',
    'Silverton' => 'Green Rugs',
    'Sky Blue' => 'Blue Rugs',
    'Smoke' => 'Black & Grey Rugs',
    'Soft Blue' => 'Blue Rugs',
    'Soft White' => 'White Rugs',
    'Steel' => 'Black & Grey Rugs',
    'Steel Blue' => 'Blue Rugs',
    'Straw' => 'Yellow & Gold Rugs',
    'Sunflower' => 'Yellow & Gold Rugs',
    'Sunshine' => 'Yellow & Gold Rugs',
    'Tan' => 'Tan & Ivories Rugs',
    'Tangerine' => 'Orange Rugs',
    'Taupe' => ['Black & Grey Rugs ','Brown Rugs'],
    'Teal' => 'Green Rugs',
    'Teal Green' => 'Green Rugs',
    'Terra Cotta' => 'Red Rugs',
    'Terracotta' => 'Red Rugs',
    'Thatch Blue' => 'Blue Rugs',
    'Thatch Light Blue' => 'Blue Rugs',
    'Turquoise' => 'Green Rugs',
    'Violet' => 'Purple Rugs',
    'Wheat' => ['Brown Rugs ','Yellow & Gold Rugs'],
    'White' => 'White Rugs',
    'White Gray' => 'White Rugs',
    'White Thatch' => 'Black & Grey Rugs',
    'White Tonal' => 'White Rugs',
    'Wood' => 'Brown Rugs',
    'Yellow' => 'Yellow & Gold Rugs',
    'Yellow Multi' => ['Multi Color Rugs' , 'Yellow & Gold Rugs']
  ];

  public static $PLUSH_PILE_NOT_SHAGS = [
    "AHM-2300",
    "AHM-2301",
    "AHM-2302",
    "AHM-2303",
    "AKR-2344",
    "AKR-2345",
    "AKR-2346",
    "AKR-2347",
    "AKR-2348",
    "AKR-2349",
    "AKR-2350",
    "AKR-2351",
    "AKR-2352",
    "AKR-2353",
    "AKR-2354",
    "APA-2308",
    "CPS-2300",
    "CPS-2302",
    "CPS-2303",
    "CPS-2306",
    "CPS-2307",
    "CPS-2308",
    "DXS-2320",
    "DXS-2321",
    "DXS-2322",
    "DXS-2323",
    "DXS-2324",
    "DXS-2325",
    "DXS-2326",
    "DXS-2327",
    "ETN-2300",
    "ETN-2301",
    "ETN-2302",
    "ETN-2303",
    "ETN-2304",
    "ETN-2305",
    "GDR-2300",
    "GDR-2301",
    "GDR-2302",
    "GDR-2304",
    "HDS-2300",
    "HDS-2301",
    "HDS-2302",
    "HDS-2303",
    "HDS-2304",
    "HDS-2305",
    "HDS-2306",
    "HDS-2308",
    "HDS-2309",
    "HDS-2310",
    "HDS-2311",
    "HDS-2312",
    "HDS-2313",
    "LOF-2300",
    "LOF-2301",
    "LOF-2302",
    "LOF-2303",
    "LOF-2304",
    "LSB-2300",
    "LSB-2301",
    "LSB-2302",
    "LSB-2303",
    "LSB-2304",
    "LYN-2300",
    "LYN-2301",
    "LYN-2302",
    "LYN-2303",
    "LYN-2304",
    "LYN-2305",
    "LYN-2306",
    "LYN-2307",
    "MRO-2300",
    "MRO-2301",
    "MRO-2302",
    "MRO-2303",
    "PFY-2302",
    "PFY-2303",
    "PFY-2304",
    "PFY-2306",
    "SHS-9600",
    "APA-2300",
    "APA-2301",
    "APA-2302",
    "APA-2303",
    "APA-2304",
    "APA-2305",
    "AME-2202",
    "CBR-8700",
    "CBR-8701",
    "CBR-8705",
    "CBR-8706",
    "CBR-8707",
    "CBR-8708",
    "CBR-8709",
    "CBR-8711",
    "CBR-8712",
    "CBR-8714",
    "CBR-8717",
    "CONFETT-10",
    "CONFETT-11",
    "CONFETT-4",
    "CONFETT-6",
    "CONFETT-8",
    "CYS-3405",
    "FLG-1000",
    "KAB-8000",
    "KAB-8001",
    "KAB-8002",
    "KAB-8003",
    "KAB-8004",
    "KAB-8005",
    "KAB-8006",
    "KAB-8007",
    "KAB-8008",
    "KAB-8009",
    "KAB-8010",
    "KAB-8011",
    "KAB-8012",
    "KAB-8013",
    "KAB-8014",
    "KAB-8015",
    "KAB-8016",
    "KAB-8017",
    "KAB-8019",
    "KAB-8020",
    "KOR-1000",
    "KOR-1001",
    "LLN-1002",
    "MDT-1000",
    "MDT-1001",
    "MDT-1002",
    "MDT-1003",
    "MDT-1004",
    "MDT-1005",
    "MDT-1006",
    "MDT-1007",
    "MDT-1008",
    "NOB-1004",
    "NOB-1007",
    "NOB-1010",
    "NOB-1013",
    "RHA-1008",
    "RHA-1020",
    "RJS-1000",
    "SBL-60",
    "SBO-6000",
    "SCO-3006",
    "SHS-9601",
    "SHS-9602",
    "WDR-2002",
    "WDR-2007",
    "WTN-5100"
  ];

}
